# Generated by Django 6.0.1 on 2026-01-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidature',
            old_name='cv',
            new_name='cv_personnalise',
        ),
    ]
