# Generated by Django 6.0.1 on 2026-01-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('en_attente', '⏳ En attente'), ('accepte', '✅ Accepté'), ('refuse', '❌ Refusé')], default='en_attente', max_length=20),
        ),
    ]
