# Generated by Django 6.0.1 on 2026-01-26 21:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_candidature_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidature',
            old_name='cv_personnalise',
            new_name='cv',
        ),
        migrations.AlterField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='offrestage',
            name='date_publication',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
